### ISSUE TITLE
Search error: no such file or directory

### ISSUE THREAD

**Issue by neomagic75** [thomas-pedersen/cursor-chat-browser#1]
Sounds like an awesome project but I can't make the search work:

1 of 1 error
Next.js (14.2.16) is outdated [(learn more)](https://nextjs.org/docs/messages/version-staleness)

Unhandled Runtime Error
TypeError: results.map is not a function

Source
src\app\search\page.tsx (85:18) @ map

  83 |
  84 |       <div className="space-y-4">
> 85 |         {results.map((result, index) => (
     |                  ^
  86 |           <Card key={index} className="p-4">
  87 |             <div className="flex items-start justify-between mb-2">
  88 |               <div>
Call Stack

 GET /api/search?q=v9&type=all 500 in 25ms
Failed to search: [Error: ENOENT: no such file or directory, scandir ''] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: ''
}

**Comment by coljac** [comment]
I had the same error trying to access any workspaces or chats. It seems the workspace settings weren't saving properly. I put this in a .env file and reran `npm run dev`, and it worked:

`WORKSPACE_PATH="/home/YOUR_USERNAME/.config/Cursor/User/workspaceStorage"`

**Comment by CoralBlade** [comment]
> I had the same error trying to access any workspaces or chats. It seems the workspace settings weren't saving properly. I put this in a .env file and reran `npm run dev`, and it worked:
> 
> `WORKSPACE_PATH="/home/YOUR_USERNAME/.config/Cursor/User/workspaceStorage"`

Great, it works! Thanks a lot for the quick help. 🙏

**Comment by bossjones** [comment]
helped me as well, thanks so much, and thank you for this tool!

**Comment by neomagic75** [comment]
Tried again, it's working like a charm now ☺️

Thanks for this valuable tool!

**Comment by thomas-pedersen** [comment]
Thanks for the feedback guys. I'll get the readme updated. Apparently the auto detection of workspace path doesn't work on all systems.
